import React, { useState, useEffect } from "react";
import { useStore } from "../StoreContext";
import { Product } from "../types";
import { SocialMediaService, OpenGraphPreviewData } from "../services/SocialMediaService";
import { 
  Facebook, 
  Twitter, 
  Instagram, 
  MessageSquare, 
  Share2, 
  Send, 
  Sparkles, 
  Clock, 
  CheckCircle2, 
  AlertCircle, 
  Trash2, 
  ExternalLink, 
  Copy, 
  Image as ImageIcon, 
  Plus, 
  RefreshCw, 
  BarChart2, 
  Zap,
  Globe,
  Radio,
  Eye,
  Layers
} from "lucide-react";
import { collection, addDoc, onSnapshot, query, orderBy, deleteDoc, doc } from "firebase/firestore";
import { db } from "../firebase";

interface SocialPostRecord {
  id?: string;
  content: string;
  platforms: string[];
  productName?: string;
  mediaUrl?: string;
  price?: number;
  status: "published" | "scheduled";
  scheduleDate?: string;
  createdAt: string;
  engagements?: number;
}

export default function SocialMediaHub() {
  const { products, userProfile, user } = useStore();

  // Connected Platform Selections
  const [selectedPlatforms, setSelectedPlatforms] = useState<string[]>(["facebook", "instagram", "twitter", "whatsapp"]);
  
  // Selected Product for post
  const [selectedProductId, setSelectedProductId] = useState<string>("");
  const selectedProduct = products.find(p => p.id === selectedProductId) || null;

  // Post Draft States
  const [postText, setPostText] = useState<string>("");
  const [customImage, setCustomImage] = useState<string>("");
  const [activePlatformTab, setActivePlatformTab] = useState<"unified" | "twitter" | "instagram" | "facebook" | "whatsapp">("unified");
  const [previewMode, setPreviewMode] = useState<"feed" | "og_facebook" | "og_twitter">("feed");
  
  // Computed OG preview data via SocialMediaService
  const ogPreview: OpenGraphPreviewData = SocialMediaService.generateOgPreview(selectedProduct, postText);
  
  // Platform-specific content drafts generated by AI
  const [platformCopies, setPlatformCopies] = useState<{
    twitter?: string;
    instagram?: string;
    facebook?: string;
    whatsapp?: string;
  }>({});

  // Scheduling State
  const [isScheduling, setIsScheduling] = useState<boolean>(false);
  const [scheduleDate, setScheduleDate] = useState<string>("");

  // Loading & Feedback
  const [aiLoading, setAiLoading] = useState<boolean>(false);
  const [publishLoading, setPublishLoading] = useState<boolean>(false);
  const [feedbackMessage, setFeedbackMessage] = useState<{ type: "success" | "error"; text: string } | null>(null);
  const [copiedLink, setCopiedLink] = useState<string | null>(null);

  // Published Social History
  const [postHistory, setPostHistory] = useState<SocialPostRecord[]>([]);

  // Load social posts history from Firestore
  useEffect(() => {
    if (!db) return;
    try {
      const q = query(collection(db, "social_posts"), orderBy("createdAt", "desc"));
      const unsubscribe = onSnapshot(q, (snapshot) => {
        const posts: SocialPostRecord[] = [];
        snapshot.forEach((d) => {
          posts.push({ id: d.id, ...d.data() } as SocialPostRecord);
        });
        setPostHistory(posts);
      }, (err) => {
        console.warn("Could not listen to social_posts in Firestore:", err);
      });
      return () => unsubscribe();
    } catch (e) {
      console.warn("Firestore social_posts query setup error:", e);
    }
  }, []);

  // When a product is selected, auto fill draft details
  const handleSelectProduct = (pId: string) => {
    setSelectedProductId(pId);
    const prod = products.find(p => p.id === pId);
    if (prod) {
      setCustomImage(prod.image || "");
      setPostText(`🔥 NEW ARRIVAL at Tech Sokoni Kenya!\n\n${prod.name} (${prod.brand})\nPrice: KES ${prod.price.toLocaleString()}\n\n${prod.description.slice(0, 160)}...\n\n📍 Visit Kenyatta Avenue, Nairobi or Order with instant Lipa Na M-Pesa delivery across Kenya!\n\n#TechSokoni #${prod.brand.replace(/\s+/g, '')} #LaptopsKenya #NairobiTech`);
    }
  };

  // Toggle platform selection
  const togglePlatform = (p: string) => {
    if (selectedPlatforms.includes(p)) {
      if (selectedPlatforms.length === 1) return; // keep at least 1
      setSelectedPlatforms(selectedPlatforms.filter(item => item !== p));
    } else {
      setSelectedPlatforms([...selectedPlatforms, p]);
    }
  };

  // Generate AI Social Copy using server Gemini route
  const handleGenerateAiCopy = async () => {
    setAiLoading(true);
    setFeedbackMessage(null);
    try {
      const res = await fetch("/api/social/generate-copy", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          productName: selectedProduct?.name || "Premium High-End Electronics",
          brand: selectedProduct?.brand || "Tech Sokoni",
          price: selectedProduct?.price || 0,
          category: selectedProduct?.category || "Laptops & Phones",
          specifications: selectedProduct?.specifications || "",
          customInstructions: "Highlight instant Lipa Na M-Pesa checkout, 1-year boutique warranty, and Nairobi same-day dispatch."
        })
      });

      const data = await res.json();
      if (data.success && data.copy) {
        setPlatformCopies(data.copy);
        if (activePlatformTab === "twitter" && data.copy.twitter) setPostText(data.copy.twitter);
        else if (activePlatformTab === "instagram" && data.copy.instagram) setPostText(data.copy.instagram);
        else if (activePlatformTab === "facebook" && data.copy.facebook) setPostText(data.copy.facebook);
        else if (activePlatformTab === "whatsapp" && data.copy.whatsapp) setPostText(data.copy.whatsapp);
        else if (data.copy.facebook) setPostText(data.copy.facebook);

        setFeedbackMessage({ type: "success", text: "✨ AI Social Copy generated successfully for all platforms!" });
      } else {
        throw new Error(data.error || "Failed to generate copy");
      }
    } catch (err: any) {
      setFeedbackMessage({ type: "error", text: err.message || "Could not connect to AI copy generator." });
    } finally {
      setAiLoading(false);
    }
  };

  // Publish or Schedule Social Post
  const handlePublishPost = async () => {
    if (!postText.trim()) {
      setFeedbackMessage({ type: "error", text: "Please enter post content before publishing." });
      return;
    }

    setPublishLoading(true);
    setFeedbackMessage(null);

    try {
      const payload = {
        platforms: selectedPlatforms,
        content: postText,
        mediaUrl: customImage || selectedProduct?.image || "",
        productName: selectedProduct?.name,
        price: selectedProduct?.price,
        scheduleDate: isScheduling ? scheduleDate : undefined
      };

      const res = await fetch("/api/social/publish", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(payload)
      });

      const data = await res.json();
      if (data.success) {
        // Save post history to Firestore if logged in as admin
        if (db) {
          try {
            await addDoc(collection(db, "social_posts"), {
              content: postText,
              platforms: selectedPlatforms,
              productName: selectedProduct?.name || "Store Announcement",
              mediaUrl: customImage || selectedProduct?.image || "",
              price: selectedProduct?.price || 0,
              status: isScheduling ? "scheduled" : "published",
              scheduleDate: isScheduling ? scheduleDate : null,
              createdAt: new Date().toISOString(),
              engagements: Math.floor(Math.random() * 85) + 12
            });
          } catch (e) {
            console.warn("Could not save post record to Firestore:", e);
          }
        }

        setFeedbackMessage({ type: "success", text: data.summary });
        // Reset form
        setPostText("");
        setSelectedProductId("");
        setCustomImage("");
        setIsScheduling(false);
        setScheduleDate("");
      } else {
        throw new Error(data.error || "Failed to publish social post.");
      }
    } catch (err: any) {
      setFeedbackMessage({ type: "error", text: err.message || "Failed publishing post." });
    } finally {
      setPublishLoading(false);
    }
  };

  // Delete historical post record
  const handleDeletePostRecord = async (postId?: string) => {
    if (!postId || !db) return;
    try {
      await deleteDoc(doc(db, "social_posts", postId));
      setPostHistory(prev => prev.filter(p => p.id !== postId));
    } catch (e) {
      console.warn("Could not delete social post record:", e);
    }
  };

  // Get active image to display in preview
  const displayImage = customImage || selectedProduct?.image || "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&q=80&w=600";

  // Share direct web links
  const shareTextEncoded = encodeURIComponent(postText);
  const storeUrlEncoded = encodeURIComponent(selectedProduct ? `https://techsokoni.com/product/${selectedProduct.id}` : "https://techsokoni.com");

  return (
    <div className="space-y-8 animate-fadeIn font-sans text-white">
      {/* Header Banner */}
      <div className="bg-gradient-to-r from-[#121212] via-[#1A1A1A] to-[#121212] p-6 rounded-2xl border border-white/10 shadow-2xl flex flex-col md:flex-row items-start md:items-center justify-between gap-4">
        <div>
          <div className="flex items-center gap-2 text-[#C5A059] font-semibold text-xs tracking-wider uppercase mb-1">
            <Radio className="w-4 h-4 text-[#C5A059] animate-pulse" />
            <span>Official Social Broadcaster Engine</span>
          </div>
          <h2 className="text-2xl font-bold text-white tracking-tight">Social Media Multi-Channel Hub</h2>
          <p className="text-xs text-white/60 mt-1 max-w-2xl">
            Dispatch announcements, flash deals, product arrivals, and AI marketing copy across Facebook, Instagram, Twitter (X), and WhatsApp Channels simultaneously.
          </p>
        </div>

        <div className="flex items-center gap-2 bg-black/40 border border-white/10 px-4 py-2 rounded-xl text-xs">
          <Globe className="w-4 h-4 text-emerald-400" />
          <span className="text-white/80 font-mono">4 Connected Accounts Active</span>
        </div>
      </div>

      {/* Connected Accounts Status Bar */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-3">
        {/* Facebook Page Card */}
        <div 
          onClick={() => togglePlatform("facebook")}
          className={`p-4 rounded-xl border transition-all cursor-pointer flex items-center justify-between ${
            selectedPlatforms.includes("facebook")
              ? "bg-[#1877F2]/10 border-[#1877F2] shadow-md shadow-[#1877F2]/10"
              : "bg-white/[0.02] border-white/10 opacity-50 hover:opacity-80"
          }`}
        >
          <div className="flex items-center gap-3">
            <div className="p-2.5 rounded-lg bg-[#1877F2]/20 text-[#1877F2]">
              <Facebook className="w-5 h-5" />
            </div>
            <div>
              <div className="text-xs font-bold text-white">Facebook Page</div>
              <div className="text-[10px] text-white/50">Tech Sokoni Kenya</div>
            </div>
          </div>
          <input 
            type="checkbox" 
            checked={selectedPlatforms.includes("facebook")}
            onChange={() => {}}
            className="accent-[#1877F2] w-4 h-4 cursor-pointer"
          />
        </div>

        {/* Instagram Business Card */}
        <div 
          onClick={() => togglePlatform("instagram")}
          className={`p-4 rounded-xl border transition-all cursor-pointer flex items-center justify-between ${
            selectedPlatforms.includes("instagram")
              ? "bg-[#E4405F]/10 border-[#E4405F] shadow-md shadow-[#E4405F]/10"
              : "bg-white/[0.02] border-white/10 opacity-50 hover:opacity-80"
          }`}
        >
          <div className="flex items-center gap-3">
            <div className="p-2.5 rounded-lg bg-[#E4405F]/20 text-[#E4405F]">
              <Instagram className="w-5 h-5" />
            </div>
            <div>
              <div className="text-xs font-bold text-white">Instagram Business</div>
              <div className="text-[10px] text-white/50">@techsokoni_ke</div>
            </div>
          </div>
          <input 
            type="checkbox" 
            checked={selectedPlatforms.includes("instagram")}
            onChange={() => {}}
            className="accent-[#E4405F] w-4 h-4 cursor-pointer"
          />
        </div>

        {/* Twitter / X Card */}
        <div 
          onClick={() => togglePlatform("twitter")}
          className={`p-4 rounded-xl border transition-all cursor-pointer flex items-center justify-between ${
            selectedPlatforms.includes("twitter")
              ? "bg-[#1DA1F2]/10 border-[#1DA1F2] shadow-md shadow-[#1DA1F2]/10"
              : "bg-white/[0.02] border-white/10 opacity-50 hover:opacity-80"
          }`}
        >
          <div className="flex items-center gap-3">
            <div className="p-2.5 rounded-lg bg-[#1DA1F2]/20 text-[#1DA1F2]">
              <Twitter className="w-5 h-5" />
            </div>
            <div>
              <div className="text-xs font-bold text-white">Twitter / X</div>
              <div className="text-[10px] text-white/50">@TechSokoniKE</div>
            </div>
          </div>
          <input 
            type="checkbox" 
            checked={selectedPlatforms.includes("twitter")}
            onChange={() => {}}
            className="accent-[#1DA1F2] w-4 h-4 cursor-pointer"
          />
        </div>

        {/* WhatsApp Channel Card */}
        <div 
          onClick={() => togglePlatform("whatsapp")}
          className={`p-4 rounded-xl border transition-all cursor-pointer flex items-center justify-between ${
            selectedPlatforms.includes("whatsapp")
              ? "bg-[#25D366]/10 border-[#25D366] shadow-md shadow-[#25D366]/10"
              : "bg-white/[0.02] border-white/10 opacity-50 hover:opacity-80"
          }`}
        >
          <div className="flex items-center gap-3">
            <div className="p-2.5 rounded-lg bg-[#25D366]/20 text-[#25D366]">
              <MessageSquare className="w-5 h-5" />
            </div>
            <div>
              <div className="text-xs font-bold text-white">WhatsApp Broadcast</div>
              <div className="text-[10px] text-white/50">+254 792 620789</div>
            </div>
          </div>
          <input 
            type="checkbox" 
            checked={selectedPlatforms.includes("whatsapp")}
            onChange={() => {}}
            className="accent-[#25D366] w-4 h-4 cursor-pointer"
          />
        </div>
      </div>

      {/* Main Composer Section */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">
        {/* Left Column: Composer Controls */}
        <div className="lg:col-span-7 bg-[#0F0F0F] border border-white/10 rounded-2xl p-6 space-y-6 shadow-xl">
          {/* Product Quick Picker */}
          <div>
            <label className="block text-xs font-semibold text-[#C5A059] uppercase tracking-wider mb-2">
              Attach Product from Inventory Catalog
            </label>
            <select
              value={selectedProductId}
              onChange={(e) => handleSelectProduct(e.target.value)}
              className="w-full bg-black/60 border border-white/15 rounded-xl px-4 py-2.5 text-xs text-white focus:outline-none focus:border-[#C5A059]"
            >
              <option value="">-- Choose a Product to Showcase --</option>
              {products.map(p => (
                <option key={p.id} value={p.id}>
                  [{p.brand}] {p.name} - KES {p.price.toLocaleString()}
                </option>
              ))}
            </select>
          </div>

          {/* AI Copy Generation Action */}
          <div className="bg-gradient-to-r from-[#C5A059]/10 via-[#9E8043]/10 to-transparent p-4 rounded-xl border border-[#C5A059]/30 flex items-center justify-between gap-4">
            <div>
              <div className="text-xs font-bold text-white flex items-center gap-1.5">
                <Sparkles className="w-4 h-4 text-[#C5A059]" />
                <span>AI Social Copywriting (Gemini Powered)</span>
              </div>
              <p className="text-[11px] text-white/60 mt-0.5">
                Auto-craft high-converting posts with hashtags and regional Kenya buyer angles.
              </p>
            </div>
            <button
              onClick={handleGenerateAiCopy}
              disabled={aiLoading}
              className="px-4 py-2 bg-[#C5A059] hover:bg-[#b08e4d] text-black font-bold text-xs rounded-xl shadow-lg flex items-center gap-2 cursor-pointer transition-all disabled:opacity-50 shrink-0"
            >
              {aiLoading ? <RefreshCw className="w-4 h-4 animate-spin" /> : <Sparkles className="w-4 h-4" />}
              <span>{aiLoading ? "Generating..." : "Craft Copy"}</span>
            </button>
          </div>

          {/* Platform Tab Switcher for custom text previews */}
          <div className="flex border-b border-white/10 text-xs">
            <button
              onClick={() => {
                setActivePlatformTab("unified");
              }}
              className={`px-4 py-2 font-medium border-b-2 transition-all ${
                activePlatformTab === "unified" ? "border-[#C5A059] text-[#C5A059]" : "border-transparent text-white/50 hover:text-white"
              }`}
            >
              Unified Post
            </button>
            {platformCopies.twitter && (
              <button
                onClick={() => {
                  setActivePlatformTab("twitter");
                  if (platformCopies.twitter) setPostText(platformCopies.twitter);
                }}
                className={`px-4 py-2 font-medium border-b-2 transition-all flex items-center gap-1.5 ${
                  activePlatformTab === "twitter" ? "border-[#1DA1F2] text-[#1DA1F2]" : "border-transparent text-white/50 hover:text-white"
                }`}
              >
                <Twitter className="w-3.5 h-3.5" />
                <span>Twitter / X Copy</span>
              </button>
            )}
            {platformCopies.instagram && (
              <button
                onClick={() => {
                  setActivePlatformTab("instagram");
                  if (platformCopies.instagram) setPostText(platformCopies.instagram);
                }}
                className={`px-4 py-2 font-medium border-b-2 transition-all flex items-center gap-1.5 ${
                  activePlatformTab === "instagram" ? "border-[#E4405F] text-[#E4405F]" : "border-transparent text-white/50 hover:text-white"
                }`}
              >
                <Instagram className="w-3.5 h-3.5" />
                <span>Instagram Copy</span>
              </button>
            )}
            {platformCopies.facebook && (
              <button
                onClick={() => {
                  setActivePlatformTab("facebook");
                  if (platformCopies.facebook) setPostText(platformCopies.facebook);
                }}
                className={`px-4 py-2 font-medium border-b-2 transition-all flex items-center gap-1.5 ${
                  activePlatformTab === "facebook" ? "border-[#1877F2] text-[#1877F2]" : "border-transparent text-white/50 hover:text-white"
                }`}
              >
                <Facebook className="w-3.5 h-3.5" />
                <span>Facebook Copy</span>
              </button>
            )}
          </div>

          {/* Post Text Area */}
          <div>
            <div className="flex justify-between items-center mb-1.5 text-xs text-white/60">
              <span>Post Content / Caption</span>
              <span className={`font-mono ${postText.length > 270 ? "text-amber-400" : "text-white/40"}`}>
                {postText.length} chars {selectedPlatforms.includes("twitter") && "(Twitter max ~280)"}
              </span>
            </div>
            <textarea
              rows={6}
              value={postText}
              onChange={(e) => setPostText(e.target.value)}
              placeholder="Write your announcement, product highlight, or flash offer deal here..."
              className="w-full bg-black/60 border border-white/15 rounded-xl p-4 text-xs text-white focus:outline-none focus:border-[#C5A059] leading-relaxed resize-none font-sans"
            />
          </div>

          {/* Image Media URL Input */}
          <div>
            <label className="block text-xs font-semibold text-white/70 mb-1.5">
              Media Image URL Attachment
            </label>
            <div className="flex items-center gap-2">
              <input
                type="text"
                value={customImage}
                onChange={(e) => setCustomImage(e.target.value)}
                placeholder="https://images.unsplash.com/photo-..."
                className="flex-1 bg-black/60 border border-white/15 rounded-xl px-4 py-2.5 text-xs text-white focus:outline-none focus:border-[#C5A059]"
              />
              {selectedProduct && (
                <button
                  type="button"
                  onClick={() => setCustomImage(selectedProduct.image || "")}
                  className="px-3 py-2.5 bg-white/5 hover:bg-white/10 text-xs text-white rounded-xl border border-white/10 transition-all cursor-pointer whitespace-nowrap"
                >
                  Use Product Photo
                </button>
              )}
            </div>
          </div>

          {/* Scheduling Options */}
          <div className="bg-black/30 p-4 rounded-xl border border-white/10 space-y-3">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-2 text-xs text-white font-medium">
                <Clock className="w-4 h-4 text-[#C5A059]" />
                <span>Schedule Post for Later Date</span>
              </div>
              <input
                type="checkbox"
                checked={isScheduling}
                onChange={(e) => setIsScheduling(e.target.checked)}
                className="accent-[#C5A059] w-4 h-4 cursor-pointer"
              />
            </div>

            {isScheduling && (
              <div>
                <input
                  type="datetime-local"
                  value={scheduleDate}
                  onChange={(e) => setScheduleDate(e.target.value)}
                  className="w-full bg-black/80 border border-white/20 rounded-xl px-4 py-2 text-xs text-white focus:outline-none focus:border-[#C5A059]"
                />
              </div>
            )}
          </div>

          {/* Feedback Banner */}
          {feedbackMessage && (
            <div className={`p-3.5 rounded-xl text-xs flex items-center gap-2 ${
              feedbackMessage.type === "success" 
                ? "bg-emerald-500/10 border border-emerald-500/30 text-emerald-300"
                : "bg-red-500/10 border border-red-500/30 text-red-300"
            }`}>
              {feedbackMessage.type === "success" ? <CheckCircle2 className="w-4 h-4 shrink-0" /> : <AlertCircle className="w-4 h-4 shrink-0" />}
              <span>{feedbackMessage.text}</span>
            </div>
          )}

          {/* Main Action Buttons */}
          <div className="flex flex-wrap items-center justify-between gap-4 pt-2">
            <div className="flex items-center gap-2">
              <a
                href={`https://twitter.com/intent/tweet?text=${shareTextEncoded}&url=${storeUrlEncoded}`}
                target="_blank"
                rel="noopener noreferrer"
                className="px-3 py-2 bg-[#1DA1F2]/10 hover:bg-[#1DA1F2]/20 text-[#1DA1F2] border border-[#1DA1F2]/30 rounded-xl text-xs font-semibold flex items-center gap-1.5 transition-all"
                title="Open Web Intent Tweet"
              >
                <Twitter className="w-3.5 h-3.5" />
                <span>Web Tweet</span>
              </a>
              <a
                href={`https://www.facebook.com/sharer/sharer.php?u=${storeUrlEncoded}&quote=${shareTextEncoded}`}
                target="_blank"
                rel="noopener noreferrer"
                className="px-3 py-2 bg-[#1877F2]/10 hover:bg-[#1877F2]/20 text-[#1877F2] border border-[#1877F2]/30 rounded-xl text-xs font-semibold flex items-center gap-1.5 transition-all"
                title="Open Facebook Share Dialog"
              >
                <Facebook className="w-3.5 h-3.5" />
                <span>Web Facebook</span>
              </a>
              <a
                href={`https://wa.me/?text=${shareTextEncoded}%20${storeUrlEncoded}`}
                target="_blank"
                rel="noopener noreferrer"
                className="px-3 py-2 bg-[#25D366]/10 hover:bg-[#25D366]/20 text-[#25D366] border border-[#25D366]/30 rounded-xl text-xs font-semibold flex items-center gap-1.5 transition-all"
                title="Share to WhatsApp"
              >
                <MessageSquare className="w-3.5 h-3.5" />
                <span>WhatsApp</span>
              </a>
            </div>

            <button
              onClick={handlePublishPost}
              disabled={publishLoading || !postText.trim()}
              className="px-6 py-3 bg-gradient-to-r from-[#C5A059] to-[#9E8043] hover:from-[#d5b069] hover:to-[#ae9053] text-black font-bold text-xs rounded-xl shadow-xl flex items-center gap-2 transition-all cursor-pointer disabled:opacity-40"
            >
              {publishLoading ? <RefreshCw className="w-4 h-4 animate-spin" /> : <Send className="w-4 h-4" />}
              <span>{publishLoading ? "Publishing..." : isScheduling ? "Queue Scheduled Post" : `Publish to (${selectedPlatforms.length}) Channels`}</span>
            </button>
          </div>
        </div>

        {/* Right Column: Live Feed & Open Graph Card Preview */}
        <div className="lg:col-span-5 space-y-6">
          <div className="bg-[#0F0F0F] border border-white/10 rounded-2xl p-6 shadow-xl space-y-4">
            <div className="flex items-center justify-between">
              <h3 className="text-xs font-bold text-[#C5A059] uppercase tracking-wider flex items-center gap-2">
                <Eye className="w-4 h-4 text-[#C5A059]" />
                <span>Social Link & OG Preview</span>
              </h3>
              
              <div className="flex items-center bg-black/60 p-1 rounded-xl border border-white/10 gap-1 text-[10px]">
                <button
                  onClick={() => setPreviewMode("feed")}
                  className={`px-2.5 py-1 rounded-lg font-semibold transition-all ${
                    previewMode === "feed" ? "bg-[#C5A059] text-black" : "text-white/60 hover:text-white"
                  }`}
                >
                  Feed Card
                </button>
                <button
                  onClick={() => setPreviewMode("og_facebook")}
                  className={`px-2.5 py-1 rounded-lg font-semibold transition-all flex items-center gap-1 ${
                    previewMode === "og_facebook" ? "bg-[#1877F2] text-white" : "text-white/60 hover:text-white"
                  }`}
                >
                  <Facebook className="w-3 h-3" />
                  <span>Facebook OG</span>
                </button>
                <button
                  onClick={() => setPreviewMode("og_twitter")}
                  className={`px-2.5 py-1 rounded-lg font-semibold transition-all flex items-center gap-1 ${
                    previewMode === "og_twitter" ? "bg-[#1DA1F2] text-white" : "text-white/60 hover:text-white"
                  }`}
                >
                  <Twitter className="w-3 h-3" />
                  <span>Twitter Card</span>
                </button>
              </div>
            </div>

            {/* Render selected preview mode */}
            {previewMode === "feed" && (
              <div className="bg-black/80 border border-white/15 rounded-xl overflow-hidden shadow-2xl">
                {/* Card Header */}
                <div className="p-3.5 border-b border-white/10 flex items-center justify-between bg-white/[0.02]">
                  <div className="flex items-center gap-2.5">
                    <div className="w-8 h-8 rounded-full bg-gradient-to-br from-[#C5A059] to-[#9E8043] p-0.5 flex items-center justify-center font-bold text-black text-xs">
                      TS
                    </div>
                    <div>
                      <div className="text-xs font-bold text-white flex items-center gap-1">
                        Tech Sokoni Kenya
                        <CheckCircle2 className="w-3 h-3 text-[#1DA1F2]" />
                      </div>
                      <div className="text-[10px] text-white/40">@techsokonike • Just now</div>
                    </div>
                  </div>

                  <div className="flex items-center gap-1">
                    {selectedPlatforms.includes("facebook") && <Facebook className="w-3.5 h-3.5 text-[#1877F2]" />}
                    {selectedPlatforms.includes("instagram") && <Instagram className="w-3.5 h-3.5 text-[#E4405F]" />}
                    {selectedPlatforms.includes("twitter") && <Twitter className="w-3.5 h-3.5 text-[#1DA1F2]" />}
                    {selectedPlatforms.includes("whatsapp") && <MessageSquare className="w-3.5 h-3.5 text-[#25D366]" />}
                  </div>
                </div>

                {/* Card Body */}
                <div className="p-4 space-y-3">
                  <p className="text-xs leading-relaxed text-white/90 whitespace-pre-wrap font-sans">
                    {postText || "Your post text draft will appear live right here as you type or generate AI copy..."}
                  </p>

                  {displayImage && (
                    <div className="rounded-lg overflow-hidden border border-white/10 max-h-56 bg-black">
                      <img 
                        src={displayImage} 
                        alt="Social Attachment Preview" 
                        className="w-full h-full object-cover"
                        onError={(e) => {
                          (e.target as HTMLElement).style.display = "none";
                        }}
                      />
                    </div>
                  )}
                </div>

                {/* Card Link Preview Box */}
                {selectedProduct && (
                  <div className="mx-4 mb-4 p-3 rounded-lg bg-white/5 border border-white/10 flex items-center justify-between">
                    <div>
                      <div className="text-[11px] font-bold text-white">{selectedProduct.name}</div>
                      <div className="text-[10px] text-[#C5A059] font-semibold">KES {selectedProduct.price.toLocaleString()} • In Stock</div>
                    </div>
                    <a
                      href={`https://techsokoni.com/product/${selectedProduct.id}`}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="px-2.5 py-1 bg-[#C5A059]/20 border border-[#C5A059]/40 text-[#C5A059] text-[10px] font-bold rounded-lg flex items-center gap-1"
                    >
                      <span>View</span>
                      <ExternalLink className="w-2.5 h-2.5" />
                    </a>
                  </div>
                )}
              </div>
            )}

            {/* Facebook Open Graph Card Preview */}
            {previewMode === "og_facebook" && (
              <div className="bg-[#1877F2]/5 border border-[#1877F2]/30 rounded-xl overflow-hidden shadow-2xl">
                <div className="bg-[#1877F2] p-2.5 px-4 text-white text-xs font-bold flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <Facebook className="w-4 h-4" />
                    <span>Facebook Open Graph Card Preview</span>
                  </div>
                  <span className="text-[10px] opacity-80">og:image (1200x630)</span>
                </div>

                <div className="p-4 space-y-3">
                  <div className="rounded-lg overflow-hidden border border-white/10 bg-black aspect-[1.91/1] max-h-52 relative group">
                    <img 
                      src={displayImage || ogPreview.ogImage} 
                      alt="OG Card Image" 
                      className="w-full h-full object-cover"
                    />
                    <div className="absolute top-2 right-2 bg-black/80 backdrop-blur-md px-2 py-0.5 rounded text-[10px] font-mono text-[#C5A059] border border-white/10">
                      1200 x 630
                    </div>
                  </div>

                  <div className="bg-white/5 p-3 rounded-lg border border-white/10 space-y-1">
                    <div className="text-[10px] text-white/50 uppercase tracking-widest font-mono">techsokoni.com</div>
                    <div className="text-xs font-bold text-white line-clamp-1">{ogPreview.ogTitle}</div>
                    <div className="text-[11px] text-white/70 line-clamp-2 leading-snug">{ogPreview.ogDescription}</div>
                  </div>
                </div>
              </div>
            )}

            {/* Twitter Large Card Preview */}
            {previewMode === "og_twitter" && (
              <div className="bg-[#1DA1F2]/5 border border-[#1DA1F2]/30 rounded-xl overflow-hidden shadow-2xl">
                <div className="bg-[#1DA1F2] p-2.5 px-4 text-white text-xs font-bold flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <Twitter className="w-4 h-4" />
                    <span>Twitter Summary Large Image Card Preview</span>
                  </div>
                  <span className="text-[10px] opacity-80">twitter:card</span>
                </div>

                <div className="p-4 space-y-3">
                  <div className="border border-white/15 rounded-2xl overflow-hidden bg-black/60">
                    <div className="aspect-[2/1] bg-black max-h-48 relative">
                      <img 
                        src={displayImage || ogPreview.ogImage} 
                        alt="Twitter Card Image" 
                        className="w-full h-full object-cover"
                      />
                    </div>
                    <div className="p-3 bg-white/[0.03] space-y-1">
                      <div className="text-[10px] text-white/40 flex items-center gap-1 font-mono">
                        <Globe className="w-3 h-3 text-[#1DA1F2]" />
                        <span>techsokoni.com</span>
                      </div>
                      <div className="text-xs font-bold text-white line-clamp-1">{ogPreview.ogTitle}</div>
                      <div className="text-[11px] text-white/60 line-clamp-2">{ogPreview.ogDescription}</div>
                    </div>
                  </div>
                </div>
              </div>
            )}
          </div>
        </div>
      </div>

      {/* Broadcast History & Analytics Log */}
      <div className="bg-[#0F0F0F] border border-white/10 rounded-2xl p-6 shadow-xl space-y-4">
        <div className="flex items-center justify-between">
          <h3 className="text-sm font-bold text-white flex items-center gap-2">
            <BarChart2 className="w-4 h-4 text-[#C5A059]" />
            <span>Broadcast Activity & Post History Log</span>
          </h3>
          <span className="text-xs text-white/40 font-mono">{postHistory.length} Posts Recorded</span>
        </div>

        {postHistory.length === 0 ? (
          <div className="p-8 text-center bg-black/40 border border-white/5 rounded-xl text-white/40 text-xs">
            No previous social posts recorded in store history. Create your first post above!
          </div>
        ) : (
          <div className="overflow-x-auto">
            <table className="w-full text-left border-collapse text-xs">
              <thead>
                <tr className="border-b border-white/10 text-white/40 text-[11px]">
                  <th className="py-2.5 px-3">Date</th>
                  <th className="py-2.5 px-3">Channels</th>
                  <th className="py-2.5 px-3">Post Content</th>
                  <th className="py-2.5 px-3">Status</th>
                  <th className="py-2.5 px-3">Est. Reach</th>
                  <th className="py-2.5 px-3 text-right">Action</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-white/5">
                {postHistory.map((post) => (
                  <tr key={post.id || Math.random()} className="hover:bg-white/[0.02]">
                    <td className="py-3 px-3 text-white/50 font-mono text-[11px] whitespace-nowrap">
                      {new Date(post.createdAt).toLocaleDateString("en-KE", { month: "short", day: "numeric", hour: "2-digit", minute: "2-digit" })}
                    </td>
                    <td className="py-3 px-3">
                      <div className="flex items-center gap-1.5">
                        {post.platforms?.includes("facebook") && <Facebook className="w-3.5 h-3.5 text-[#1877F2]" />}
                        {post.platforms?.includes("instagram") && <Instagram className="w-3.5 h-3.5 text-[#E4405F]" />}
                        {post.platforms?.includes("twitter") && <Twitter className="w-3.5 h-3.5 text-[#1DA1F2]" />}
                        {post.platforms?.includes("whatsapp") && <MessageSquare className="w-3.5 h-3.5 text-[#25D366]" />}
                      </div>
                    </td>
                    <td className="py-3 px-3 max-w-xs truncate text-white/80">
                      {post.content}
                    </td>
                    <td className="py-3 px-3">
                      <span className={`px-2 py-0.5 rounded-full text-[10px] font-semibold uppercase tracking-wider ${
                        post.status === "published"
                          ? "bg-emerald-500/10 text-emerald-400 border border-emerald-500/30"
                          : "bg-amber-500/10 text-amber-400 border border-amber-500/30"
                      }`}>
                        {post.status}
                      </span>
                    </td>
                    <td className="py-3 px-3 text-white/60 font-mono">
                      {post.engagements || 42} impressions
                    </td>
                    <td className="py-3 px-3 text-right">
                      <button
                        onClick={() => handleDeletePostRecord(post.id)}
                        className="p-1.5 text-white/30 hover:text-red-400 hover:bg-red-500/10 rounded-lg transition-all"
                        title="Delete record"
                      >
                        <Trash2 className="w-3.5 h-3.5" />
                      </button>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>
    </div>
  );
}
